### ISSUE TITLE
Custom mustache file seem ignored

### ISSUE THREAD

**Issue by Sami32** [jakubplichta/git-changelog-maven-plugin#19]
The custom mustache file seem ignored by `templateFile`:
`<templateFile>${project.basedir}/src/resources/releasenotes.mustache</templateFile>`

_releasenotes.mustache_
```
# {{reportTitle}}

{{#tags}}
## {{name}}
    {{#commits}}
* {{#extensions.pullRequest}}
    {{/commits}}

{{/tags}}
```

As no error or warning is displayed and that the result is always the same i guess that it use the plugin default mustache file.
Except if my mustache file have some mistake that are not reported.

**EDIT**:
I tried like that as well without more success:
```
# {{reportTitle}}

{{#tags}}
## {{name}}
    {{#commits}}
* [PR #{{id}}]
    {{/commits}}

{{/tags}}
```
or
```
# {{reportTitle}}

{{#tags}}
## {{name}}

{{/tags}}
```

**Comment by alireza-sadeghias** [comment]
a little late may be bug fixed or sth else
but this works for me
<plugin>
<groupId>se.bjurr.gitchangelog</groupId>
<artifactId>git-changelog-maven-plugin</artifactId>
<version>1.92</version>
<executions>
	<execution>
		<id>GenerateGitChangelog</id>
		<phase>generate-sources</phase>
		<goals>
			<goal>git-changelog</goal>
		</goals>
		<configuration>
			<templateFile>${project.basedir}/src/main/resources/changelog.mustache</templateFile>
		</configuration>
	</execution>
</executions>
</plugin>

**Comment by Sami32** [comment]
Thanks for your feedback +1
I don't use it anymore but i probably will in the future.
